//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Original file name:
// Generation date: 11/11/2014 15:46:57
namespace Client.AIO
{
    
    /// <summary>
    /// There are no comments for Container in the schema.
    /// </summary>
    public partial class Container : global::System.Data.Services.Client.DataServiceContext
    {
        /// <summary>
        /// Initialize a new Container object.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public Container(global::System.Uri serviceRoot) : 
                base(serviceRoot, global::System.Data.Services.Common.DataServiceProtocolVersion.V3)
        {
            this.ResolveName = new global::System.Func<global::System.Type, string>(this.ResolveNameFromType);
            this.ResolveType = new global::System.Func<string, global::System.Type>(this.ResolveTypeFromName);
            this.OnContextCreated();
            this.Format.LoadServiceModel = GeneratedEdmModel.GetInstance;
        }
        partial void OnContextCreated();
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected global::System.Type ResolveTypeFromName(string typeName)
        {
            global::System.Type resolvedType = this.DefaultResolveType(typeName, "ACES.Models", "Client.AIO");
            if ((resolvedType != null))
            {
                return resolvedType;
            }
            return null;
        }
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected string ResolveNameFromType(global::System.Type clientType)
        {
            if (clientType.Namespace.Equals("Client.AIO", global::System.StringComparison.Ordinal))
            {
                return string.Concat("ACES.Models.", clientType.Name);
            }
            return null;
        }
        /// <summary>
        /// There are no comments for Activities in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<Activity> Activities
        {
            get
            {
                if ((this._Activities == null))
                {
                    this._Activities = base.CreateQuery<Activity>("Activities");
                }
                return this._Activities;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<Activity> _Activities;
        /// <summary>
        /// There are no comments for AppPackages in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<AppPackage> AppPackages
        {
            get
            {
                if ((this._AppPackages == null))
                {
                    this._AppPackages = base.CreateQuery<AppPackage>("AppPackages");
                }
                return this._AppPackages;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<AppPackage> _AppPackages;
        /// <summary>
        /// There are no comments for WorkItems in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<WorkItem> WorkItems
        {
            get
            {
                if ((this._WorkItems == null))
                {
                    this._WorkItems = base.CreateQuery<WorkItem>("WorkItems");
                }
                return this._WorkItems;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<WorkItem> _WorkItems;
        /// <summary>
        /// There are no comments for Activities in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToActivities(Activity activity)
        {
            base.AddObject("Activities", activity);
        }
        /// <summary>
        /// There are no comments for AppPackages in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToAppPackages(AppPackage appPackage)
        {
            base.AddObject("AppPackages", appPackage);
        }
        /// <summary>
        /// There are no comments for WorkItems in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToWorkItems(WorkItem workItem)
        {
            base.AddObject("WorkItems", workItem);
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private abstract class GeneratedEdmModel
        {
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static global::Microsoft.Data.Edm.IEdmModel ParsedModel = LoadModelFromString();
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private const string ModelPart0 = "<edmx:Edmx Version=\"1.0\" xmlns:edmx=\"http://schemas.microsoft.com/ado/2007/06/edm" +
                "x\"><edmx:DataServices m:DataServiceVersion=\"3.0\" m:MaxDataServiceVersion=\"3.0\" x" +
                "mlns:m=\"http://schemas.microsoft.com/ado/2007/08/dataservices/metadata\"><Schema " +
                "Namespace=\"ACES.Models\" xmlns=\"http://schemas.microsoft.com/ado/2009/11/edm\"><En" +
                "tityType Name=\"Activity\"><Key><PropertyRef Name=\"Id\" /><PropertyRef Name=\"UserId" +
                "\" /></Key><Property Name=\"RequiredEngineVersion\" Type=\"Edm.String\" Nullable=\"fal" +
                "se\" /><Property Name=\"Parameters\" Type=\"ACES.Models.Parameters\" Nullable=\"false\"" +
                " /><Property Name=\"Instruction\" Type=\"ACES.Models.Instruction\" /><Property Name=" +
                "\"AllowedChildProcesses\" Type=\"Collection(ACES.Models.AllowedChildProcess)\" Nulla" +
                "ble=\"false\" /><Property Name=\"Version\" Type=\"Edm.Int32\" Nullable=\"false\" /><Prop" +
                "erty Name=\"Timestamp\" Type=\"Edm.DateTimeOffset\" Nullable=\"false\" /><Property Nam" +
                "e=\"UserId\" Type=\"Edm.String\" Nullable=\"false\" /><Property Name=\"Id\" Type=\"Edm.St" +
                "ring\" Nullable=\"false\" /><NavigationProperty Name=\"AppPackages\" Relationship=\"AC" +
                "ES.Models.ACES_Models_Activity_AppPackages_ACES_Models_AppPackage_AppPackagesPar" +
                "tner\" ToRole=\"AppPackages\" FromRole=\"AppPackagesPartner\" /></EntityType><EntityT" +
                "ype Name=\"AppPackage\"><Key><PropertyRef Name=\"Id\" /><PropertyRef Name=\"UserId\" /" +
                "></Key><Property Name=\"Resource\" Type=\"Edm.String\" /><Property Name=\"RequiredEng" +
                "ineVersion\" Type=\"Edm.String\" /><Property Name=\"Version\" Type=\"Edm.Int32\" Nullab" +
                "le=\"false\" /><Property Name=\"Timestamp\" Type=\"Edm.DateTimeOffset\" Nullable=\"fals" +
                "e\" /><Property Name=\"UserId\" Type=\"Edm.String\" Nullable=\"false\" /><Property Name" +
                "=\"Id\" Type=\"Edm.String\" Nullable=\"false\" /><NavigationProperty Name=\"References\"" +
                " Relationship=\"ACES.Models.ACES_Models_AppPackage_References_ACES_Models_AppPack" +
                "age_ReferencesPartner\" ToRole=\"References\" FromRole=\"ReferencesPartner\" /></Enti" +
                "tyType><EntityType Name=\"WorkItem\"><Key><PropertyRef Name=\"Id\" /><PropertyRef Na" +
                "me=\"UserId\" /></Key><Property Name=\"Arguments\" Type=\"ACES.Models.Arguments\" Null" +
                "able=\"false\" /><Property Name=\"Status\" Type=\"Edm.String\" /><Property Name=\"Statu" +
                "sDetails\" Type=\"ACES.Models.StatusDetails\" /><Property Name=\"AvailabilityZone\" T" +
                "ype=\"Edm.String\" /><Property Name=\"ActivityId\" Type=\"ACES.Models.EntityId\" /><Pr" +
                "operty Name=\"TimeQueued\" Type=\"Edm.DateTime\" /><Property Name=\"TimeInputTransfer" +
                "Started\" Type=\"Edm.DateTime\" /><Property Name=\"TimeScriptStarted\" Type=\"Edm.Date" +
                "Time\" /><Property Name=\"TimeScriptEnded\" Type=\"Edm.DateTime\" /><Property Name=\"T" +
                "imeOutputTransferEnded\" Type=\"Edm.DateTime\" /><Property Name=\"BytesTranferredIn\"" +
                " Type=\"Edm.Int64\" /><Property Name=\"BytesTranferredOut\" Type=\"Edm.Int64\" /><Prop" +
                "erty Name=\"Version\" Type=\"Edm.Int32\" Nullable=\"false\" /><Property Name=\"Timestam" +
                "p\" Type=\"Edm.DateTimeOffset\" Nullable=\"false\" /><Property Name=\"UserId\" Type=\"Ed" +
                "m.String\" Nullable=\"false\" /><Property Name=\"Id\" Type=\"Edm.String\" Nullable=\"fal" +
                "se\" /><NavigationProperty Name=\"Activity\" Relationship=\"ACES.Models.ACES_Models_" +
                "WorkItem_Activity_ACES_Models_Activity_ActivityPartner\" ToRole=\"Activity\" FromRo" +
                "le=\"ActivityPartner\" /></EntityType><EntityType Name=\"RemoteFile\"><Key><Property" +
                "Ref Name=\"Resource\" /></Key><Property Name=\"UserId\" Type=\"Edm.String\" /><Propert" +
                "y Name=\"Version\" Type=\"Edm.Int32\" Nullable=\"false\" /><Property Name=\"Resource\" T" +
                "ype=\"Edm.String\" Nullable=\"false\" /><Property Name=\"LocalFileName\" Type=\"Edm.Str" +
                "ing\" Nullable=\"false\" /><NavigationProperty Name=\"RelatedFiles\" Relationship=\"AC" +
                "ES.Models.ACES_Models_RemoteFile_RelatedFiles_ACES_Models_RemoteFile_RelatedFile" +
                "sPartner\" ToRole=\"RelatedFiles\" FromRole=\"RelatedFilesPartner\" /></EntityType><C" +
                "omplexType Name=\"EntityId\"><Property Name=\"UserId\" Type=\"Edm.String\" /><Property" +
                " Name=\"Id\" Type=\"Edm.String\" /></ComplexType><ComplexType Name=\"Parameters\"><Pro" +
                "perty Name=\"InputParameters\" Type=\"Collection(ACES.Models.Parameter)\" Nullable=\"" +
                "false\" /><Property Name=\"OutputParameters\" Type=\"Collection(ACES.Models.Paramete" +
                "r)\" Nullable=\"false\" /></ComplexType><ComplexType Name=\"Arguments\"><Property Nam" +
                "e=\"InputArguments\" Type=\"Collection(ACES.Models.Argument)\" Nullable=\"false\" /><P" +
                "roperty Name=\"OutputArguments\" Type=\"Collection(ACES.Models.Argument)\" Nullable=" +
                "\"false\" /></ComplexType><ComplexType Name=\"Parameter\"><Property Name=\"Name\" Type" +
                "=\"Edm.String\" Nullable=\"false\" /><Property Name=\"LocalFileName\" Type=\"Edm.String" +
                "\" Nullable=\"false\" /></ComplexType><ComplexType Name=\"Instruction\"><Property Nam" +
                "e=\"CommandLineParameters\" Type=\"Edm.String\" /><Property Name=\"Script\" Type=\"Edm." +
                "String\" /></ComplexType><ComplexType Name=\"AllowedChildProcess\"><Property Name=\"" +
                "Name\" Type=\"Edm.String\" /><Property Name=\"RelativePath\" Type=\"Edm.String\" /></Co" +
                "mplexType><ComplexType Name=\"Argument\"><Property Name=\"Resource\" Type=\"Edm.Strin" +
                "g\" /><Property Name=\"Name\" Type=\"Edm.String\" Nullable=\"false\" /><Property Name=\"" +
                "Authentication\" Type=\"Edm.String\" /><Property Name=\"ResourceKind\" Type=\"Edm.Stri" +
                "ng\" /><Property Name=\"StorageProvider\" Type=\"Edm.String\" /><Property Name=\"HttpV" +
                "erb\" Type=\"Edm.String\" /></ComplexType><ComplexType Name=\"StatusDetails\"><Proper" +
                "ty Name=\"Report\" Type=\"Edm.String\" /></ComplexType><Association Name=\"ACES_Model" +
                "s_Activity_AppPackages_ACES_Models_AppPackage_AppPackagesPartner\"><End Type=\"ACE" +
                "S.Models.AppPackage\" Role=\"AppPackages\" Multiplicity=\"*\" /><End Type=\"ACES.Model" +
                "s.Activity\" Role=\"AppPackagesPartner\" Multiplicity=\"0..1\" /></Association><Assoc" +
                "iation Name=\"ACES_Models_AppPackage_References_ACES_Models_AppPackage_References" +
                "Partner\"><End Type=\"ACES.Models.AppPackage\" Role=\"References\" Multiplicity=\"*\" /" +
                "><End Type=\"ACES.Models.AppPackage\" Role=\"ReferencesPartner\" Multiplicity=\"0..1\"" +
                " /></Association><Association Name=\"ACES_Models_WorkItem_Activity_ACES_Models_Ac" +
                "tivity_ActivityPartner\"><End Type=\"ACES.Models.Activity\" Role=\"Activity\" Multipl" +
                "icity=\"0..1\" /><End Type=\"ACES.Models.WorkItem\" Role=\"ActivityPartner\" Multiplic" +
                "ity=\"0..1\" /></Association><Association Name=\"ACES_Models_RemoteFile_RelatedFile" +
                "s_ACES_Models_RemoteFile_RelatedFilesPartner\"><End Type=\"ACES.Models.RemoteFile\"" +
                " Role=\"RelatedFiles\" Multiplicity=\"*\" /><End Type=\"ACES.Models.RemoteFile\" Role=" +
                "\"RelatedFilesPartner\" Multiplicity=\"0..1\" /></Association></Schema><Schema Names" +
                "pace=\"Default\" xmlns=\"http://schemas.microsoft.com/ado/2009/11/edm\"><EntityConta" +
                "iner Name=\"Container\" m:IsDefaultEntityContainer=\"true\"><EntitySet Name=\"Activit" +
                "ies\" EntityType=\"ACES.Models.Activity\" /><EntitySet Name=\"AppPackages\" EntityTyp" +
                "e=\"ACES.Models.AppPackage\" /><EntitySet Name=\"WorkItems\" EntityType=\"ACES.Models" +
                ".WorkItem\" /><FunctionImport Name=\"GenerateUploadUrl\" ReturnType=\"Edm.String\" Is" +
                "Bindable=\"true\" m:IsAlwaysBindable=\"true\"><Parameter Name=\"bindingParameter\" Typ" +
                "e=\"Collection(ACES.Models.AppPackage)\" Nullable=\"false\" /></FunctionImport><Asso" +
                "ciationSet Name=\"ACES_Models_Activity_AppPackages_ACES_Models_AppPackage_AppPack" +
                "agesPartnerSet\" Association=\"ACES.Models.ACES_Models_Activity_AppPackages_ACES_M" +
                "odels_AppPackage_AppPackagesPartner\"><End Role=\"AppPackagesPartner\" EntitySet=\"A" +
                "ctivities\" /><End Role=\"AppPackages\" EntitySet=\"AppPackages\" /></AssociationSet>" +
                "<AssociationSet Name=\"ACES_Models_AppPackage_References_ACES_Models_AppPackage_R" +
                "eferencesPartnerSet\" Association=\"ACES.Models.ACES_Models_AppPackage_References_" +
                "ACES_Models_AppPackage_ReferencesPartner\"><End Role=\"ReferencesPartner\" EntitySe" +
                "t=\"AppPackages\" /><End Role=\"References\" EntitySet=\"AppPackages\" /></Association" +
                "Set><AssociationSet Name=\"ACES_Models_WorkItem_Activity_ACES_Models_Activity_Act" +
                "ivityPartnerSet\" Association=\"ACES.Models.ACES_Models_WorkI";
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private const string ModelPart1 = "tem_Activity_ACES_Models_Activity_ActivityPartner\"><End Role=\"ActivityPartner\" En" +
                "titySet=\"WorkItems\" /><End Role=\"Activity\" EntitySet=\"Activities\" /></Associatio" +
                "nSet></EntityContainer></Schema></edmx:DataServices></edmx:Edmx>";
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static string GetConcatenatedEdmxString()
            {
                return string.Concat(ModelPart0, ModelPart1);
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            public static global::Microsoft.Data.Edm.IEdmModel GetInstance()
            {
                return ParsedModel;
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static global::Microsoft.Data.Edm.IEdmModel LoadModelFromString()
            {
                string edmxToParse = GetConcatenatedEdmxString();
                global::System.Xml.XmlReader reader = CreateXmlReader(edmxToParse);
                try
                {
                    return global::Microsoft.Data.Edm.Csdl.EdmxReader.Parse(reader);
                }
                finally
                {
                    ((global::System.IDisposable)(reader)).Dispose();
                }
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static global::System.Xml.XmlReader CreateXmlReader(string edmxToParse)
            {
                return global::System.Xml.XmlReader.Create(new global::System.IO.StringReader(edmxToParse));
            }
        }
    }
    /// <summary>
    /// There are no comments for ComplexType ACES.Models.Parameters in the schema.
    /// </summary>
    public partial class Parameters : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new Parameters object.
        /// </summary>
        /// <param name="inputParameters">Initial value of InputParameters.</param>
        /// <param name="outputParameters">Initial value of OutputParameters.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static Parameters CreateParameters(global::System.Collections.ObjectModel.ObservableCollection<Parameter> inputParameters, global::System.Collections.ObjectModel.ObservableCollection<Parameter> outputParameters)
        {
            Parameters parameters = new Parameters();
            if ((inputParameters == null))
            {
                throw new global::System.ArgumentNullException("inputParameters");
            }
            parameters.InputParameters = inputParameters;
            if ((outputParameters == null))
            {
                throw new global::System.ArgumentNullException("outputParameters");
            }
            parameters.OutputParameters = outputParameters;
            return parameters;
        }
        /// <summary>
        /// There are no comments for Property InputParameters in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Collections.ObjectModel.ObservableCollection<Parameter> InputParameters
        {
            get
            {
                return this._InputParameters;
            }
            set
            {
                this.OnInputParametersChanging(value);
                this._InputParameters = value;
                this.OnInputParametersChanged();
                this.OnPropertyChanged("InputParameters");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Collections.ObjectModel.ObservableCollection<Parameter> _InputParameters = new global::System.Collections.ObjectModel.ObservableCollection<Parameter>();
        partial void OnInputParametersChanging(global::System.Collections.ObjectModel.ObservableCollection<Parameter> value);
        partial void OnInputParametersChanged();
        /// <summary>
        /// There are no comments for Property OutputParameters in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Collections.ObjectModel.ObservableCollection<Parameter> OutputParameters
        {
            get
            {
                return this._OutputParameters;
            }
            set
            {
                this.OnOutputParametersChanging(value);
                this._OutputParameters = value;
                this.OnOutputParametersChanged();
                this.OnPropertyChanged("OutputParameters");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Collections.ObjectModel.ObservableCollection<Parameter> _OutputParameters = new global::System.Collections.ObjectModel.ObservableCollection<Parameter>();
        partial void OnOutputParametersChanging(global::System.Collections.ObjectModel.ObservableCollection<Parameter> value);
        partial void OnOutputParametersChanged();
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for ComplexType ACES.Models.Parameter in the schema.
    /// </summary>
    public partial class Parameter : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new Parameter object.
        /// </summary>
        /// <param name="name">Initial value of Name.</param>
        /// <param name="localFileName">Initial value of LocalFileName.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static Parameter CreateParameter(string name, string localFileName)
        {
            Parameter parameter = new Parameter();
            parameter.Name = name;
            parameter.LocalFileName = localFileName;
            return parameter;
        }
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this._Name = value;
                this.OnNameChanged();
                this.OnPropertyChanged("Name");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Property LocalFileName in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string LocalFileName
        {
            get
            {
                return this._LocalFileName;
            }
            set
            {
                this.OnLocalFileNameChanging(value);
                this._LocalFileName = value;
                this.OnLocalFileNameChanged();
                this.OnPropertyChanged("LocalFileName");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _LocalFileName;
        partial void OnLocalFileNameChanging(string value);
        partial void OnLocalFileNameChanged();
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for ComplexType ACES.Models.Instruction in the schema.
    /// </summary>
    public partial class Instruction : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// There are no comments for Property CommandLineParameters in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string CommandLineParameters
        {
            get
            {
                return this._CommandLineParameters;
            }
            set
            {
                this.OnCommandLineParametersChanging(value);
                this._CommandLineParameters = value;
                this.OnCommandLineParametersChanged();
                this.OnPropertyChanged("CommandLineParameters");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _CommandLineParameters;
        partial void OnCommandLineParametersChanging(string value);
        partial void OnCommandLineParametersChanged();
        /// <summary>
        /// There are no comments for Property Script in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Script
        {
            get
            {
                return this._Script;
            }
            set
            {
                this.OnScriptChanging(value);
                this._Script = value;
                this.OnScriptChanged();
                this.OnPropertyChanged("Script");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Script;
        partial void OnScriptChanging(string value);
        partial void OnScriptChanged();
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for ComplexType ACES.Models.AllowedChildProcess in the schema.
    /// </summary>
    public partial class AllowedChildProcess : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this._Name = value;
                this.OnNameChanged();
                this.OnPropertyChanged("Name");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Property RelativePath in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string RelativePath
        {
            get
            {
                return this._RelativePath;
            }
            set
            {
                this.OnRelativePathChanging(value);
                this._RelativePath = value;
                this.OnRelativePathChanged();
                this.OnPropertyChanged("RelativePath");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _RelativePath;
        partial void OnRelativePathChanging(string value);
        partial void OnRelativePathChanged();
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for ACES.Models.Activity in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// UserId
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("Activities")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id", "UserId")]
    public partial class Activity : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new Activity object.
        /// </summary>
        /// <param name="requiredEngineVersion">Initial value of RequiredEngineVersion.</param>
        /// <param name="parameters">Initial value of Parameters.</param>
        /// <param name="allowedChildProcesses">Initial value of AllowedChildProcesses.</param>
        /// <param name="version">Initial value of Version.</param>
        /// <param name="timestamp">Initial value of Timestamp.</param>
        /// <param name="userId">Initial value of UserId.</param>
        /// <param name="ID">Initial value of Id.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static Activity CreateActivity(string requiredEngineVersion, Parameters parameters, global::System.Collections.ObjectModel.ObservableCollection<AllowedChildProcess> allowedChildProcesses, int version, global::System.DateTimeOffset timestamp, string userId, string ID)
        {
            Activity activity = new Activity();
            activity.RequiredEngineVersion = requiredEngineVersion;
            if ((parameters == null))
            {
                throw new global::System.ArgumentNullException("parameters");
            }
            activity.Parameters = parameters;
            if ((allowedChildProcesses == null))
            {
                throw new global::System.ArgumentNullException("allowedChildProcesses");
            }
            activity.AllowedChildProcesses = allowedChildProcesses;
            activity.Version = version;
            activity.Timestamp = timestamp;
            activity.UserId = userId;
            activity.Id = ID;
            return activity;
        }
        /// <summary>
        /// There are no comments for Property RequiredEngineVersion in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string RequiredEngineVersion
        {
            get
            {
                return this._RequiredEngineVersion;
            }
            set
            {
                this.OnRequiredEngineVersionChanging(value);
                this._RequiredEngineVersion = value;
                this.OnRequiredEngineVersionChanged();
                this.OnPropertyChanged("RequiredEngineVersion");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _RequiredEngineVersion;
        partial void OnRequiredEngineVersionChanging(string value);
        partial void OnRequiredEngineVersionChanged();
        /// <summary>
        /// There are no comments for Property Parameters in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public Parameters Parameters
        {
            get
            {
                if (((this._Parameters == null) 
                            && (this._ParametersInitialized != true)))
                {
                    this._Parameters = new Parameters();
                    this._ParametersInitialized = true;
                }
                return this._Parameters;
            }
            set
            {
                this.OnParametersChanging(value);
                this._Parameters = value;
                this._ParametersInitialized = true;
                this.OnParametersChanged();
                this.OnPropertyChanged("Parameters");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private Parameters _Parameters;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private bool _ParametersInitialized;
        partial void OnParametersChanging(Parameters value);
        partial void OnParametersChanged();
        /// <summary>
        /// There are no comments for Property Instruction in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public Instruction Instruction
        {
            get
            {
                if (((this._Instruction == null) 
                            && (this._InstructionInitialized != true)))
                {
                    this._Instruction = new Instruction();
                    this._InstructionInitialized = true;
                }
                return this._Instruction;
            }
            set
            {
                this.OnInstructionChanging(value);
                this._Instruction = value;
                this._InstructionInitialized = true;
                this.OnInstructionChanged();
                this.OnPropertyChanged("Instruction");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private Instruction _Instruction;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private bool _InstructionInitialized;
        partial void OnInstructionChanging(Instruction value);
        partial void OnInstructionChanged();
        /// <summary>
        /// There are no comments for Property AllowedChildProcesses in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Collections.ObjectModel.ObservableCollection<AllowedChildProcess> AllowedChildProcesses
        {
            get
            {
                return this._AllowedChildProcesses;
            }
            set
            {
                this.OnAllowedChildProcessesChanging(value);
                this._AllowedChildProcesses = value;
                this.OnAllowedChildProcessesChanged();
                this.OnPropertyChanged("AllowedChildProcesses");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Collections.ObjectModel.ObservableCollection<AllowedChildProcess> _AllowedChildProcesses = new global::System.Collections.ObjectModel.ObservableCollection<AllowedChildProcess>();
        partial void OnAllowedChildProcessesChanging(global::System.Collections.ObjectModel.ObservableCollection<AllowedChildProcess> value);
        partial void OnAllowedChildProcessesChanged();
        /// <summary>
        /// There are no comments for Property Version in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Version
        {
            get
            {
                return this._Version;
            }
            set
            {
                this.OnVersionChanging(value);
                this._Version = value;
                this.OnVersionChanged();
                this.OnPropertyChanged("Version");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Version;
        partial void OnVersionChanging(int value);
        partial void OnVersionChanged();
        /// <summary>
        /// There are no comments for Property Timestamp in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.DateTimeOffset Timestamp
        {
            get
            {
                return this._Timestamp;
            }
            set
            {
                this.OnTimestampChanging(value);
                this._Timestamp = value;
                this.OnTimestampChanged();
                this.OnPropertyChanged("Timestamp");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.DateTimeOffset _Timestamp;
        partial void OnTimestampChanging(global::System.DateTimeOffset value);
        partial void OnTimestampChanged();
        /// <summary>
        /// There are no comments for Property UserId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string UserId
        {
            get
            {
                return this._UserId;
            }
            set
            {
                this.OnUserIdChanging(value);
                this._UserId = value;
                this.OnUserIdChanged();
                this.OnPropertyChanged("UserId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _UserId;
        partial void OnUserIdChanging(string value);
        partial void OnUserIdChanged();
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Id;
        partial void OnIdChanging(string value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for AppPackages in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<AppPackage> AppPackages
        {
            get
            {
                return this._AppPackages;
            }
            set
            {
                this._AppPackages = value;
                this.OnPropertyChanged("AppPackages");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<AppPackage> _AppPackages = new global::System.Data.Services.Client.DataServiceCollection<AppPackage>(null, global::System.Data.Services.Client.TrackingMode.None);
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for ACES.Models.AppPackage in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// UserId
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("AppPackages")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id", "UserId")]
    public partial class AppPackage : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new AppPackage object.
        /// </summary>
        /// <param name="version">Initial value of Version.</param>
        /// <param name="timestamp">Initial value of Timestamp.</param>
        /// <param name="userId">Initial value of UserId.</param>
        /// <param name="ID">Initial value of Id.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static AppPackage CreateAppPackage(int version, global::System.DateTimeOffset timestamp, string userId, string ID)
        {
            AppPackage appPackage = new AppPackage();
            appPackage.Version = version;
            appPackage.Timestamp = timestamp;
            appPackage.UserId = userId;
            appPackage.Id = ID;
            return appPackage;
        }
        /// <summary>
        /// There are no comments for Property Resource in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Resource
        {
            get
            {
                return this._Resource;
            }
            set
            {
                this.OnResourceChanging(value);
                this._Resource = value;
                this.OnResourceChanged();
                this.OnPropertyChanged("Resource");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Resource;
        partial void OnResourceChanging(string value);
        partial void OnResourceChanged();
        /// <summary>
        /// There are no comments for Property RequiredEngineVersion in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string RequiredEngineVersion
        {
            get
            {
                return this._RequiredEngineVersion;
            }
            set
            {
                this.OnRequiredEngineVersionChanging(value);
                this._RequiredEngineVersion = value;
                this.OnRequiredEngineVersionChanged();
                this.OnPropertyChanged("RequiredEngineVersion");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _RequiredEngineVersion;
        partial void OnRequiredEngineVersionChanging(string value);
        partial void OnRequiredEngineVersionChanged();
        /// <summary>
        /// There are no comments for Property Version in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Version
        {
            get
            {
                return this._Version;
            }
            set
            {
                this.OnVersionChanging(value);
                this._Version = value;
                this.OnVersionChanged();
                this.OnPropertyChanged("Version");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Version;
        partial void OnVersionChanging(int value);
        partial void OnVersionChanged();
        /// <summary>
        /// There are no comments for Property Timestamp in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.DateTimeOffset Timestamp
        {
            get
            {
                return this._Timestamp;
            }
            set
            {
                this.OnTimestampChanging(value);
                this._Timestamp = value;
                this.OnTimestampChanged();
                this.OnPropertyChanged("Timestamp");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.DateTimeOffset _Timestamp;
        partial void OnTimestampChanging(global::System.DateTimeOffset value);
        partial void OnTimestampChanged();
        /// <summary>
        /// There are no comments for Property UserId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string UserId
        {
            get
            {
                return this._UserId;
            }
            set
            {
                this.OnUserIdChanging(value);
                this._UserId = value;
                this.OnUserIdChanged();
                this.OnPropertyChanged("UserId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _UserId;
        partial void OnUserIdChanging(string value);
        partial void OnUserIdChanged();
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Id;
        partial void OnIdChanging(string value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for References in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<AppPackage> References
        {
            get
            {
                return this._References;
            }
            set
            {
                this._References = value;
                this.OnPropertyChanged("References");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<AppPackage> _References = new global::System.Data.Services.Client.DataServiceCollection<AppPackage>(null, global::System.Data.Services.Client.TrackingMode.None);
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for ComplexType ACES.Models.Arguments in the schema.
    /// </summary>
    public partial class Arguments : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new Arguments object.
        /// </summary>
        /// <param name="inputArguments">Initial value of InputArguments.</param>
        /// <param name="outputArguments">Initial value of OutputArguments.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static Arguments CreateArguments(global::System.Collections.ObjectModel.ObservableCollection<Argument> inputArguments, global::System.Collections.ObjectModel.ObservableCollection<Argument> outputArguments)
        {
            Arguments arguments = new Arguments();
            if ((inputArguments == null))
            {
                throw new global::System.ArgumentNullException("inputArguments");
            }
            arguments.InputArguments = inputArguments;
            if ((outputArguments == null))
            {
                throw new global::System.ArgumentNullException("outputArguments");
            }
            arguments.OutputArguments = outputArguments;
            return arguments;
        }
        /// <summary>
        /// There are no comments for Property InputArguments in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Collections.ObjectModel.ObservableCollection<Argument> InputArguments
        {
            get
            {
                return this._InputArguments;
            }
            set
            {
                this.OnInputArgumentsChanging(value);
                this._InputArguments = value;
                this.OnInputArgumentsChanged();
                this.OnPropertyChanged("InputArguments");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Collections.ObjectModel.ObservableCollection<Argument> _InputArguments = new global::System.Collections.ObjectModel.ObservableCollection<Argument>();
        partial void OnInputArgumentsChanging(global::System.Collections.ObjectModel.ObservableCollection<Argument> value);
        partial void OnInputArgumentsChanged();
        /// <summary>
        /// There are no comments for Property OutputArguments in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Collections.ObjectModel.ObservableCollection<Argument> OutputArguments
        {
            get
            {
                return this._OutputArguments;
            }
            set
            {
                this.OnOutputArgumentsChanging(value);
                this._OutputArguments = value;
                this.OnOutputArgumentsChanged();
                this.OnPropertyChanged("OutputArguments");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Collections.ObjectModel.ObservableCollection<Argument> _OutputArguments = new global::System.Collections.ObjectModel.ObservableCollection<Argument>();
        partial void OnOutputArgumentsChanging(global::System.Collections.ObjectModel.ObservableCollection<Argument> value);
        partial void OnOutputArgumentsChanged();
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for ComplexType ACES.Models.Argument in the schema.
    /// </summary>
    public partial class Argument : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new Argument object.
        /// </summary>
        /// <param name="name">Initial value of Name.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static Argument CreateArgument(string name)
        {
            Argument argument = new Argument();
            argument.Name = name;
            return argument;
        }
        /// <summary>
        /// There are no comments for Property Resource in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Resource
        {
            get
            {
                return this._Resource;
            }
            set
            {
                this.OnResourceChanging(value);
                this._Resource = value;
                this.OnResourceChanged();
                this.OnPropertyChanged("Resource");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Resource;
        partial void OnResourceChanging(string value);
        partial void OnResourceChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this._Name = value;
                this.OnNameChanged();
                this.OnPropertyChanged("Name");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Property Authentication in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Authentication
        {
            get
            {
                return this._Authentication;
            }
            set
            {
                this.OnAuthenticationChanging(value);
                this._Authentication = value;
                this.OnAuthenticationChanged();
                this.OnPropertyChanged("Authentication");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Authentication;
        partial void OnAuthenticationChanging(string value);
        partial void OnAuthenticationChanged();
        /// <summary>
        /// There are no comments for Property ResourceKind in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string ResourceKind
        {
            get
            {
                return this._ResourceKind;
            }
            set
            {
                this.OnResourceKindChanging(value);
                this._ResourceKind = value;
                this.OnResourceKindChanged();
                this.OnPropertyChanged("ResourceKind");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _ResourceKind;
        partial void OnResourceKindChanging(string value);
        partial void OnResourceKindChanged();
        /// <summary>
        /// There are no comments for Property StorageProvider in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string StorageProvider
        {
            get
            {
                return this._StorageProvider;
            }
            set
            {
                this.OnStorageProviderChanging(value);
                this._StorageProvider = value;
                this.OnStorageProviderChanged();
                this.OnPropertyChanged("StorageProvider");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _StorageProvider;
        partial void OnStorageProviderChanging(string value);
        partial void OnStorageProviderChanged();
        /// <summary>
        /// There are no comments for Property HttpVerb in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string HttpVerb
        {
            get
            {
                return this._HttpVerb;
            }
            set
            {
                this.OnHttpVerbChanging(value);
                this._HttpVerb = value;
                this.OnHttpVerbChanged();
                this.OnPropertyChanged("HttpVerb");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _HttpVerb;
        partial void OnHttpVerbChanging(string value);
        partial void OnHttpVerbChanged();
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for ComplexType ACES.Models.StatusDetails in the schema.
    /// </summary>
    public partial class StatusDetails : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// There are no comments for Property Report in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Report
        {
            get
            {
                return this._Report;
            }
            set
            {
                this.OnReportChanging(value);
                this._Report = value;
                this.OnReportChanged();
                this.OnPropertyChanged("Report");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Report;
        partial void OnReportChanging(string value);
        partial void OnReportChanged();
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for ComplexType ACES.Models.EntityId in the schema.
    /// </summary>
    public partial class EntityId : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// There are no comments for Property UserId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string UserId
        {
            get
            {
                return this._UserId;
            }
            set
            {
                this.OnUserIdChanging(value);
                this._UserId = value;
                this.OnUserIdChanged();
                this.OnPropertyChanged("UserId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _UserId;
        partial void OnUserIdChanging(string value);
        partial void OnUserIdChanged();
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Id;
        partial void OnIdChanging(string value);
        partial void OnIdChanged();
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for ACES.Models.WorkItem in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// UserId
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("WorkItems")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id", "UserId")]
    public partial class WorkItem : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new WorkItem object.
        /// </summary>
        /// <param name="arguments">Initial value of Arguments.</param>
        /// <param name="version">Initial value of Version.</param>
        /// <param name="timestamp">Initial value of Timestamp.</param>
        /// <param name="userId">Initial value of UserId.</param>
        /// <param name="ID">Initial value of Id.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static WorkItem CreateWorkItem(Arguments arguments, int version, global::System.DateTimeOffset timestamp, string userId, string ID)
        {
            WorkItem workItem = new WorkItem();
            if ((arguments == null))
            {
                throw new global::System.ArgumentNullException("arguments");
            }
            workItem.Arguments = arguments;
            workItem.Version = version;
            workItem.Timestamp = timestamp;
            workItem.UserId = userId;
            workItem.Id = ID;
            return workItem;
        }
        /// <summary>
        /// There are no comments for Property Arguments in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public Arguments Arguments
        {
            get
            {
                if (((this._Arguments == null) 
                            && (this._ArgumentsInitialized != true)))
                {
                    this._Arguments = new Arguments();
                    this._ArgumentsInitialized = true;
                }
                return this._Arguments;
            }
            set
            {
                this.OnArgumentsChanging(value);
                this._Arguments = value;
                this._ArgumentsInitialized = true;
                this.OnArgumentsChanged();
                this.OnPropertyChanged("Arguments");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private Arguments _Arguments;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private bool _ArgumentsInitialized;
        partial void OnArgumentsChanging(Arguments value);
        partial void OnArgumentsChanged();
        /// <summary>
        /// There are no comments for Property Status in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Status
        {
            get
            {
                return this._Status;
            }
            set
            {
                this.OnStatusChanging(value);
                this._Status = value;
                this.OnStatusChanged();
                this.OnPropertyChanged("Status");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Status;
        partial void OnStatusChanging(string value);
        partial void OnStatusChanged();
        /// <summary>
        /// There are no comments for Property StatusDetails in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public StatusDetails StatusDetails
        {
            get
            {
                if (((this._StatusDetails == null) 
                            && (this._StatusDetailsInitialized != true)))
                {
                    this._StatusDetails = new StatusDetails();
                    this._StatusDetailsInitialized = true;
                }
                return this._StatusDetails;
            }
            set
            {
                this.OnStatusDetailsChanging(value);
                this._StatusDetails = value;
                this._StatusDetailsInitialized = true;
                this.OnStatusDetailsChanged();
                this.OnPropertyChanged("StatusDetails");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private StatusDetails _StatusDetails;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private bool _StatusDetailsInitialized;
        partial void OnStatusDetailsChanging(StatusDetails value);
        partial void OnStatusDetailsChanged();
        /// <summary>
        /// There are no comments for Property AvailabilityZone in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string AvailabilityZone
        {
            get
            {
                return this._AvailabilityZone;
            }
            set
            {
                this.OnAvailabilityZoneChanging(value);
                this._AvailabilityZone = value;
                this.OnAvailabilityZoneChanged();
                this.OnPropertyChanged("AvailabilityZone");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _AvailabilityZone;
        partial void OnAvailabilityZoneChanging(string value);
        partial void OnAvailabilityZoneChanged();
        /// <summary>
        /// There are no comments for Property ActivityId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public EntityId ActivityId
        {
            get
            {
                if (((this._ActivityId == null) 
                            && (this._ActivityIdInitialized != true)))
                {
                    this._ActivityId = new EntityId();
                    this._ActivityIdInitialized = true;
                }
                return this._ActivityId;
            }
            set
            {
                this.OnActivityIdChanging(value);
                this._ActivityId = value;
                this._ActivityIdInitialized = true;
                this.OnActivityIdChanged();
                this.OnPropertyChanged("ActivityId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private EntityId _ActivityId;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private bool _ActivityIdInitialized;
        partial void OnActivityIdChanging(EntityId value);
        partial void OnActivityIdChanged();
        /// <summary>
        /// There are no comments for Property TimeQueued in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<global::System.DateTime> TimeQueued
        {
            get
            {
                return this._TimeQueued;
            }
            set
            {
                this.OnTimeQueuedChanging(value);
                this._TimeQueued = value;
                this.OnTimeQueuedChanged();
                this.OnPropertyChanged("TimeQueued");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<global::System.DateTime> _TimeQueued;
        partial void OnTimeQueuedChanging(global::System.Nullable<global::System.DateTime> value);
        partial void OnTimeQueuedChanged();
        /// <summary>
        /// There are no comments for Property TimeInputTransferStarted in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<global::System.DateTime> TimeInputTransferStarted
        {
            get
            {
                return this._TimeInputTransferStarted;
            }
            set
            {
                this.OnTimeInputTransferStartedChanging(value);
                this._TimeInputTransferStarted = value;
                this.OnTimeInputTransferStartedChanged();
                this.OnPropertyChanged("TimeInputTransferStarted");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<global::System.DateTime> _TimeInputTransferStarted;
        partial void OnTimeInputTransferStartedChanging(global::System.Nullable<global::System.DateTime> value);
        partial void OnTimeInputTransferStartedChanged();
        /// <summary>
        /// There are no comments for Property TimeScriptStarted in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<global::System.DateTime> TimeScriptStarted
        {
            get
            {
                return this._TimeScriptStarted;
            }
            set
            {
                this.OnTimeScriptStartedChanging(value);
                this._TimeScriptStarted = value;
                this.OnTimeScriptStartedChanged();
                this.OnPropertyChanged("TimeScriptStarted");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<global::System.DateTime> _TimeScriptStarted;
        partial void OnTimeScriptStartedChanging(global::System.Nullable<global::System.DateTime> value);
        partial void OnTimeScriptStartedChanged();
        /// <summary>
        /// There are no comments for Property TimeScriptEnded in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<global::System.DateTime> TimeScriptEnded
        {
            get
            {
                return this._TimeScriptEnded;
            }
            set
            {
                this.OnTimeScriptEndedChanging(value);
                this._TimeScriptEnded = value;
                this.OnTimeScriptEndedChanged();
                this.OnPropertyChanged("TimeScriptEnded");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<global::System.DateTime> _TimeScriptEnded;
        partial void OnTimeScriptEndedChanging(global::System.Nullable<global::System.DateTime> value);
        partial void OnTimeScriptEndedChanged();
        /// <summary>
        /// There are no comments for Property TimeOutputTransferEnded in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<global::System.DateTime> TimeOutputTransferEnded
        {
            get
            {
                return this._TimeOutputTransferEnded;
            }
            set
            {
                this.OnTimeOutputTransferEndedChanging(value);
                this._TimeOutputTransferEnded = value;
                this.OnTimeOutputTransferEndedChanged();
                this.OnPropertyChanged("TimeOutputTransferEnded");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<global::System.DateTime> _TimeOutputTransferEnded;
        partial void OnTimeOutputTransferEndedChanging(global::System.Nullable<global::System.DateTime> value);
        partial void OnTimeOutputTransferEndedChanged();
        /// <summary>
        /// There are no comments for Property BytesTranferredIn in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<long> BytesTranferredIn
        {
            get
            {
                return this._BytesTranferredIn;
            }
            set
            {
                this.OnBytesTranferredInChanging(value);
                this._BytesTranferredIn = value;
                this.OnBytesTranferredInChanged();
                this.OnPropertyChanged("BytesTranferredIn");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<long> _BytesTranferredIn;
        partial void OnBytesTranferredInChanging(global::System.Nullable<long> value);
        partial void OnBytesTranferredInChanged();
        /// <summary>
        /// There are no comments for Property BytesTranferredOut in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<long> BytesTranferredOut
        {
            get
            {
                return this._BytesTranferredOut;
            }
            set
            {
                this.OnBytesTranferredOutChanging(value);
                this._BytesTranferredOut = value;
                this.OnBytesTranferredOutChanged();
                this.OnPropertyChanged("BytesTranferredOut");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<long> _BytesTranferredOut;
        partial void OnBytesTranferredOutChanging(global::System.Nullable<long> value);
        partial void OnBytesTranferredOutChanged();
        /// <summary>
        /// There are no comments for Property Version in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Version
        {
            get
            {
                return this._Version;
            }
            set
            {
                this.OnVersionChanging(value);
                this._Version = value;
                this.OnVersionChanged();
                this.OnPropertyChanged("Version");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Version;
        partial void OnVersionChanging(int value);
        partial void OnVersionChanged();
        /// <summary>
        /// There are no comments for Property Timestamp in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.DateTimeOffset Timestamp
        {
            get
            {
                return this._Timestamp;
            }
            set
            {
                this.OnTimestampChanging(value);
                this._Timestamp = value;
                this.OnTimestampChanged();
                this.OnPropertyChanged("Timestamp");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.DateTimeOffset _Timestamp;
        partial void OnTimestampChanging(global::System.DateTimeOffset value);
        partial void OnTimestampChanged();
        /// <summary>
        /// There are no comments for Property UserId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string UserId
        {
            get
            {
                return this._UserId;
            }
            set
            {
                this.OnUserIdChanging(value);
                this._UserId = value;
                this.OnUserIdChanged();
                this.OnPropertyChanged("UserId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _UserId;
        partial void OnUserIdChanging(string value);
        partial void OnUserIdChanged();
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Id;
        partial void OnIdChanging(string value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Activity in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public Activity Activity
        {
            get
            {
                return this._Activity;
            }
            set
            {
                this._Activity = value;
                this.OnPropertyChanged("Activity");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private Activity _Activity;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for ACES.Models.RemoteFile in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Resource
    /// </KeyProperties>
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Resource")]
    public partial class RemoteFile : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new RemoteFile object.
        /// </summary>
        /// <param name="version">Initial value of Version.</param>
        /// <param name="resource">Initial value of Resource.</param>
        /// <param name="localFileName">Initial value of LocalFileName.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static RemoteFile CreateRemoteFile(int version, string resource, string localFileName)
        {
            RemoteFile remoteFile = new RemoteFile();
            remoteFile.Version = version;
            remoteFile.Resource = resource;
            remoteFile.LocalFileName = localFileName;
            return remoteFile;
        }
        /// <summary>
        /// There are no comments for Property UserId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string UserId
        {
            get
            {
                return this._UserId;
            }
            set
            {
                this.OnUserIdChanging(value);
                this._UserId = value;
                this.OnUserIdChanged();
                this.OnPropertyChanged("UserId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _UserId;
        partial void OnUserIdChanging(string value);
        partial void OnUserIdChanged();
        /// <summary>
        /// There are no comments for Property Version in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Version
        {
            get
            {
                return this._Version;
            }
            set
            {
                this.OnVersionChanging(value);
                this._Version = value;
                this.OnVersionChanged();
                this.OnPropertyChanged("Version");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Version;
        partial void OnVersionChanging(int value);
        partial void OnVersionChanged();
        /// <summary>
        /// There are no comments for Property Resource in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Resource
        {
            get
            {
                return this._Resource;
            }
            set
            {
                this.OnResourceChanging(value);
                this._Resource = value;
                this.OnResourceChanged();
                this.OnPropertyChanged("Resource");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Resource;
        partial void OnResourceChanging(string value);
        partial void OnResourceChanged();
        /// <summary>
        /// There are no comments for Property LocalFileName in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string LocalFileName
        {
            get
            {
                return this._LocalFileName;
            }
            set
            {
                this.OnLocalFileNameChanging(value);
                this._LocalFileName = value;
                this.OnLocalFileNameChanged();
                this.OnPropertyChanged("LocalFileName");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _LocalFileName;
        partial void OnLocalFileNameChanging(string value);
        partial void OnLocalFileNameChanged();
        /// <summary>
        /// There are no comments for RelatedFiles in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<RemoteFile> RelatedFiles
        {
            get
            {
                return this._RelatedFiles;
            }
            set
            {
                this._RelatedFiles = value;
                this.OnPropertyChanged("RelatedFiles");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<RemoteFile> _RelatedFiles = new global::System.Data.Services.Client.DataServiceCollection<RemoteFile>(null, global::System.Data.Services.Client.TrackingMode.None);
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
}
